### ISSUE TITLE
Source files look like examples

### ISSUE THREAD

**Issue by glwagner** [glwagner/Dao.jl#2]
There are a few source files in `/src` (`convenience.jl` and `uq_kpp.jl`), but the code is not contained inside modules and no functions are exported in `Dao.jl`. These source files look like examples to me.

We should develop software and functions for UQ that permit users to write simple, clear,  short and concise scripts that perform elementary UQ.

We may also want to develop 'interface' modules that interface with codes like `OceanTurb`, though I'm not sure this is necessary (it would be better to ask codes like `OceanTurb` to implement the functionality we need so that interfacing is trivial).

**Comment by sandreza** [comment]
1) The files have been moved to sandbox
2) A preliminary file has been set up to do UQ
3) Some of these files will be in the sandbox
